// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sonarr.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Api.V3.Delayprofile.Reorder.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\delayprofile\reorder\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReorderItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Delayprofile.Reorder.Item.ReorderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReorderItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/delayprofile/reorder/{id}{?after*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Delayprofile.Reorder.Item.ReorderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReorderItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/delayprofile/reorder/{id}{?after*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::Soenneker.Sonarr.OpenApiClient.Models.DelayProfileResource&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Sonarr.OpenApiClient.Models.DelayProfileResource>?> PutAsync(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Delayprofile.Reorder.Item.ReorderItemRequestBuilder.ReorderItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Sonarr.OpenApiClient.Models.DelayProfileResource>> PutAsync(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Delayprofile.Reorder.Item.ReorderItemRequestBuilder.ReorderItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Sonarr.OpenApiClient.Models.DelayProfileResource>(requestInfo, global::Soenneker.Sonarr.OpenApiClient.Models.DelayProfileResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Delayprofile.Reorder.Item.ReorderItemRequestBuilder.ReorderItemRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Delayprofile.Reorder.Item.ReorderItemRequestBuilder.ReorderItemRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Delayprofile.Reorder.Item.ReorderItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Delayprofile.Reorder.Item.ReorderItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Delayprofile.Reorder.Item.ReorderItemRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class ReorderItemRequestBuilderPutQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("after")]
            public int? After { get; set; }
        }
    }
}
#pragma warning restore CS0618
