// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.Item;
using Soenneker.Sonarr.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\wanted\cutoff
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CutoffRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Sonarr.OpenApiClient.api.v3.wanted.cutoff.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.Item.CutoffItemRequestBuilder"/></returns>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.Item.CutoffItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.Item.CutoffItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.CutoffRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CutoffRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/wanted/cutoff{?includeEpisodeFile*,includeImages*,includeSeries*,monitored*,page*,pageSize*,sortDirection*,sortKey*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.CutoffRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CutoffRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/wanted/cutoff{?includeEpisodeFile*,includeImages*,includeSeries*,monitored*,page*,pageSize*,sortDirection*,sortKey*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResourcePagingResource"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResourcePagingResource?> GetAsync(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.CutoffRequestBuilder.CutoffRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResourcePagingResource> GetAsync(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.CutoffRequestBuilder.CutoffRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResourcePagingResource>(requestInfo, global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResourcePagingResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.CutoffRequestBuilder.CutoffRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.CutoffRequestBuilder.CutoffRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.CutoffRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.CutoffRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Wanted.Cutoff.CutoffRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class CutoffRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("includeEpisodeFile")]
            public bool? IncludeEpisodeFile { get; set; }
            [QueryParameter("includeImages")]
            public bool? IncludeImages { get; set; }
            [QueryParameter("includeSeries")]
            public bool? IncludeSeries { get; set; }
            [QueryParameter("monitored")]
            public bool? Monitored { get; set; }
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
            [QueryParameter("sortDirection")]
            public global::Soenneker.Sonarr.OpenApiClient.Models.SortDirection? SortDirection { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortKey")]
            public string? SortKey { get; set; }
#nullable restore
#else
            [QueryParameter("sortKey")]
            public string SortKey { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
