// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sonarr.OpenApiClient.Api.V3.System.Backup;
using Soenneker.Sonarr.OpenApiClient.Api.V3.System.Restart;
using Soenneker.Sonarr.OpenApiClient.Api.V3.System.Routes;
using Soenneker.Sonarr.OpenApiClient.Api.V3.System.Shutdown;
using Soenneker.Sonarr.OpenApiClient.Api.V3.System.Status;
using Soenneker.Sonarr.OpenApiClient.Api.V3.System.TaskNamespace;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Api.V3.System
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\system
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SystemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The backup property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.Backup.BackupRequestBuilder Backup
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.Backup.BackupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restart property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.Restart.RestartRequestBuilder Restart
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.Restart.RestartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The routes property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.Routes.RoutesRequestBuilder Routes
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.Routes.RoutesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shutdown property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.Shutdown.ShutdownRequestBuilder Shutdown
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.Shutdown.ShutdownRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.Status.StatusRequestBuilder Status
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The task property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.TaskNamespace.TaskRequestBuilder Task
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.TaskNamespace.TaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.SystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/system", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.System.SystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/system", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
