// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.Bulk;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.Item;
using Soenneker.Sonarr.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\blocklist
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BlocklistRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bulk property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.Bulk.BulkRequestBuilder Bulk
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.Bulk.BulkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Sonarr.OpenApiClient.api.v3.blocklist.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.Item.BlocklistItemRequestBuilder"/></returns>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.Item.BlocklistItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.Item.BlocklistItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Soenneker.Sonarr.OpenApiClient.api.v3.blocklist.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.Item.BlocklistItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.Item.BlocklistItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.Item.BlocklistItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.BlocklistRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlocklistRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/blocklist{?page*,pageSize*,protocols*,seriesIds*,sortDirection*,sortKey*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.BlocklistRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlocklistRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/blocklist{?page*,pageSize*,protocols*,seriesIds*,sortDirection*,sortKey*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.BlocklistResourcePagingResource"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sonarr.OpenApiClient.Models.BlocklistResourcePagingResource?> GetAsync(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.BlocklistRequestBuilder.BlocklistRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sonarr.OpenApiClient.Models.BlocklistResourcePagingResource> GetAsync(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.BlocklistRequestBuilder.BlocklistRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sonarr.OpenApiClient.Models.BlocklistResourcePagingResource>(requestInfo, global::Soenneker.Sonarr.OpenApiClient.Models.BlocklistResourcePagingResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.BlocklistRequestBuilder.BlocklistRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.BlocklistRequestBuilder.BlocklistRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.BlocklistRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.BlocklistRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.BlocklistRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class BlocklistRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
            [Obsolete("This property is deprecated, use ProtocolsAsDownloadProtocol instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("protocols")]
            public string[]? Protocols { get; set; }
#nullable restore
#else
            [QueryParameter("protocols")]
            public string[] Protocols { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("protocols")]
            public global::Soenneker.Sonarr.OpenApiClient.Models.DownloadProtocol[]? ProtocolsAsDownloadProtocol { get; set; }
#nullable restore
#else
            [QueryParameter("protocols")]
            public global::Soenneker.Sonarr.OpenApiClient.Models.DownloadProtocol[] ProtocolsAsDownloadProtocol { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("seriesIds")]
            public int?[]? SeriesIds { get; set; }
#nullable restore
#else
            [QueryParameter("seriesIds")]
            public int?[] SeriesIds { get; set; }
#endif
            [Obsolete("This property is deprecated, use SortDirectionAsSortDirection instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortDirection")]
            public string? SortDirection { get; set; }
#nullable restore
#else
            [QueryParameter("sortDirection")]
            public string SortDirection { get; set; }
#endif
            [QueryParameter("sortDirection")]
            public global::Soenneker.Sonarr.OpenApiClient.Models.SortDirection? SortDirectionAsSortDirection { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortKey")]
            public string? SortKey { get; set; }
#nullable restore
#else
            [QueryParameter("sortKey")]
            public string SortKey { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BlocklistRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Blocklist.BlocklistRequestBuilder.BlocklistRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
