// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddSeriesOptions : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ignoreEpisodesWithFiles property</summary>
        public bool? IgnoreEpisodesWithFiles { get; set; }
        /// <summary>The ignoreEpisodesWithoutFiles property</summary>
        public bool? IgnoreEpisodesWithoutFiles { get; set; }
        /// <summary>The monitor property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.MonitorTypes? Monitor { get; set; }
        /// <summary>The searchForCutoffUnmetEpisodes property</summary>
        public bool? SearchForCutoffUnmetEpisodes { get; set; }
        /// <summary>The searchForMissingEpisodes property</summary>
        public bool? SearchForMissingEpisodes { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.AddSeriesOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.AddSeriesOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.AddSeriesOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ignoreEpisodesWithFiles", n => { IgnoreEpisodesWithFiles = n.GetBoolValue(); } },
                { "ignoreEpisodesWithoutFiles", n => { IgnoreEpisodesWithoutFiles = n.GetBoolValue(); } },
                { "monitor", n => { Monitor = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.MonitorTypes>(); } },
                { "searchForCutoffUnmetEpisodes", n => { SearchForCutoffUnmetEpisodes = n.GetBoolValue(); } },
                { "searchForMissingEpisodes", n => { SearchForMissingEpisodes = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("ignoreEpisodesWithFiles", IgnoreEpisodesWithFiles);
            writer.WriteBoolValue("ignoreEpisodesWithoutFiles", IgnoreEpisodesWithoutFiles);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.MonitorTypes>("monitor", Monitor);
            writer.WriteBoolValue("searchForCutoffUnmetEpisodes", SearchForCutoffUnmetEpisodes);
            writer.WriteBoolValue("searchForMissingEpisodes", SearchForMissingEpisodes);
        }
    }
}
#pragma warning restore CS0618
