// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AutoTaggingResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The removeTagsAutomatically property</summary>
        public bool? RemoveTagsAutomatically { get; set; }
        /// <summary>The specifications property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.AutoTaggingSpecificationSchema>? Specifications { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.AutoTaggingSpecificationSchema> Specifications { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Tags { get; set; }
#nullable restore
#else
        public List<int?> Tags { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.AutoTaggingResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.AutoTaggingResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.AutoTaggingResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "removeTagsAutomatically", n => { RemoveTagsAutomatically = n.GetBoolValue(); } },
                { "specifications", n => { Specifications = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.AutoTaggingSpecificationSchema>(global::Soenneker.Sonarr.OpenApiClient.Models.AutoTaggingSpecificationSchema.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("removeTagsAutomatically", RemoveTagsAutomatically);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.AutoTaggingSpecificationSchema>("specifications", Specifications);
            writer.WriteCollectionOfPrimitiveValues<int?>("tags", Tags);
        }
    }
}
#pragma warning restore CS0618
