// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CertificateValidationType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "enabled")]
        #pragma warning disable CS1591
        Enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "disabledForLocalAddresses")]
        #pragma warning disable CS1591
        DisabledForLocalAddresses,
        #pragma warning restore CS1591
        [EnumMember(Value = "disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
    }
}
