// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CommandResult
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "successful")]
        #pragma warning disable CS1591
        Successful,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsuccessful")]
        #pragma warning disable CS1591
        Unsuccessful,
        #pragma warning restore CS1591
    }
}
