// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CommandResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The body property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.Command? Body { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.Command Body { get; set; }
#endif
        /// <summary>The clientUserAgent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientUserAgent { get; set; }
#nullable restore
#else
        public string ClientUserAgent { get; set; }
#endif
        /// <summary>The commandName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommandName { get; set; }
#nullable restore
#else
        public string CommandName { get; set; }
#endif
        /// <summary>The duration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Duration { get; set; }
#nullable restore
#else
        public string Duration { get; set; }
#endif
        /// <summary>The ended property</summary>
        public DateTimeOffset? Ended { get; set; }
        /// <summary>The exception property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Exception { get; set; }
#nullable restore
#else
        public string Exception { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The lastExecutionTime property</summary>
        public DateTimeOffset? LastExecutionTime { get; set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The priority property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.CommandPriority? Priority { get; set; }
        /// <summary>The queued property</summary>
        public DateTimeOffset? Queued { get; set; }
        /// <summary>The result property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.CommandResult? Result { get; set; }
        /// <summary>The sendUpdatesToClient property</summary>
        public bool? SendUpdatesToClient { get; set; }
        /// <summary>The started property</summary>
        public DateTimeOffset? Started { get; set; }
        /// <summary>The stateChangeTime property</summary>
        public DateTimeOffset? StateChangeTime { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.CommandStatus? Status { get; set; }
        /// <summary>The trigger property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.CommandTrigger? Trigger { get; set; }
        /// <summary>The updateScheduledTask property</summary>
        public bool? UpdateScheduledTask { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.CommandResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.CommandResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.CommandResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "body", n => { Body = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.Command>(global::Soenneker.Sonarr.OpenApiClient.Models.Command.CreateFromDiscriminatorValue); } },
                { "clientUserAgent", n => { ClientUserAgent = n.GetStringValue(); } },
                { "commandName", n => { CommandName = n.GetStringValue(); } },
                { "duration", n => { Duration = n.GetStringValue(); } },
                { "ended", n => { Ended = n.GetDateTimeOffsetValue(); } },
                { "exception", n => { Exception = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "lastExecutionTime", n => { LastExecutionTime = n.GetDateTimeOffsetValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.CommandPriority>(); } },
                { "queued", n => { Queued = n.GetDateTimeOffsetValue(); } },
                { "result", n => { Result = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.CommandResult>(); } },
                { "sendUpdatesToClient", n => { SendUpdatesToClient = n.GetBoolValue(); } },
                { "started", n => { Started = n.GetDateTimeOffsetValue(); } },
                { "stateChangeTime", n => { StateChangeTime = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.CommandStatus>(); } },
                { "trigger", n => { Trigger = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.CommandTrigger>(); } },
                { "updateScheduledTask", n => { UpdateScheduledTask = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.Command>("body", Body);
            writer.WriteStringValue("clientUserAgent", ClientUserAgent);
            writer.WriteStringValue("commandName", CommandName);
            writer.WriteStringValue("duration", Duration);
            writer.WriteDateTimeOffsetValue("ended", Ended);
            writer.WriteStringValue("exception", Exception);
            writer.WriteIntValue("id", Id);
            writer.WriteDateTimeOffsetValue("lastExecutionTime", LastExecutionTime);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.CommandPriority>("priority", Priority);
            writer.WriteDateTimeOffsetValue("queued", Queued);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.CommandResult>("result", Result);
            writer.WriteBoolValue("sendUpdatesToClient", SendUpdatesToClient);
            writer.WriteDateTimeOffsetValue("started", Started);
            writer.WriteDateTimeOffsetValue("stateChangeTime", StateChangeTime);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.CommandStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.CommandTrigger>("trigger", Trigger);
            writer.WriteBoolValue("updateScheduledTask", UpdateScheduledTask);
        }
    }
}
#pragma warning restore CS0618
