// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomFormatSpecificationSchema : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.Field>? Fields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.Field> Fields { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The implementation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Implementation { get; set; }
#nullable restore
#else
        public string Implementation { get; set; }
#endif
        /// <summary>The implementationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImplementationName { get; set; }
#nullable restore
#else
        public string ImplementationName { get; set; }
#endif
        /// <summary>The infoLink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InfoLink { get; set; }
#nullable restore
#else
        public string InfoLink { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The negate property</summary>
        public bool? Negate { get; set; }
        /// <summary>The presets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatSpecificationSchema>? Presets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatSpecificationSchema> Presets { get; set; }
#endif
        /// <summary>The required property</summary>
        public bool? Required { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatSpecificationSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatSpecificationSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatSpecificationSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.Field>(global::Soenneker.Sonarr.OpenApiClient.Models.Field.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "implementation", n => { Implementation = n.GetStringValue(); } },
                { "implementationName", n => { ImplementationName = n.GetStringValue(); } },
                { "infoLink", n => { InfoLink = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "negate", n => { Negate = n.GetBoolValue(); } },
                { "presets", n => { Presets = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatSpecificationSchema>(global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatSpecificationSchema.CreateFromDiscriminatorValue)?.AsList(); } },
                { "required", n => { Required = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.Field>("fields", Fields);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("implementation", Implementation);
            writer.WriteStringValue("implementationName", ImplementationName);
            writer.WriteStringValue("infoLink", InfoLink);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("negate", Negate);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatSpecificationSchema>("presets", Presets);
            writer.WriteBoolValue("required", Required);
        }
    }
}
#pragma warning restore CS0618
