// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DownloadClientBulkResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The applyTags property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.ApplyTags? ApplyTags { get; set; }
        /// <summary>The enable property</summary>
        public bool? Enable { get; set; }
        /// <summary>The ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Ids { get; set; }
#nullable restore
#else
        public List<int?> Ids { get; set; }
#endif
        /// <summary>The priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The removeCompletedDownloads property</summary>
        public bool? RemoveCompletedDownloads { get; set; }
        /// <summary>The removeFailedDownloads property</summary>
        public bool? RemoveFailedDownloads { get; set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Tags { get; set; }
#nullable restore
#else
        public List<int?> Tags { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.DownloadClientBulkResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.DownloadClientBulkResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.DownloadClientBulkResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "applyTags", n => { ApplyTags = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.ApplyTags>(); } },
                { "enable", n => { Enable = n.GetBoolValue(); } },
                { "ids", n => { Ids = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "removeCompletedDownloads", n => { RemoveCompletedDownloads = n.GetBoolValue(); } },
                { "removeFailedDownloads", n => { RemoveFailedDownloads = n.GetBoolValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.ApplyTags>("applyTags", ApplyTags);
            writer.WriteBoolValue("enable", Enable);
            writer.WriteCollectionOfPrimitiveValues<int?>("ids", Ids);
            writer.WriteIntValue("priority", Priority);
            writer.WriteBoolValue("removeCompletedDownloads", RemoveCompletedDownloads);
            writer.WriteBoolValue("removeFailedDownloads", RemoveFailedDownloads);
            writer.WriteCollectionOfPrimitiveValues<int?>("tags", Tags);
        }
    }
}
#pragma warning restore CS0618
