// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DownloadClientConfigResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The autoRedownloadFailed property</summary>
        public bool? AutoRedownloadFailed { get; set; }
        /// <summary>The autoRedownloadFailedFromInteractiveSearch property</summary>
        public bool? AutoRedownloadFailedFromInteractiveSearch { get; set; }
        /// <summary>The downloadClientWorkingFolders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DownloadClientWorkingFolders { get; set; }
#nullable restore
#else
        public string DownloadClientWorkingFolders { get; set; }
#endif
        /// <summary>The enableCompletedDownloadHandling property</summary>
        public bool? EnableCompletedDownloadHandling { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.DownloadClientConfigResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.DownloadClientConfigResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.DownloadClientConfigResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoRedownloadFailed", n => { AutoRedownloadFailed = n.GetBoolValue(); } },
                { "autoRedownloadFailedFromInteractiveSearch", n => { AutoRedownloadFailedFromInteractiveSearch = n.GetBoolValue(); } },
                { "downloadClientWorkingFolders", n => { DownloadClientWorkingFolders = n.GetStringValue(); } },
                { "enableCompletedDownloadHandling", n => { EnableCompletedDownloadHandling = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("autoRedownloadFailed", AutoRedownloadFailed);
            writer.WriteBoolValue("autoRedownloadFailedFromInteractiveSearch", AutoRedownloadFailedFromInteractiveSearch);
            writer.WriteStringValue("downloadClientWorkingFolders", DownloadClientWorkingFolders);
            writer.WriteBoolValue("enableCompletedDownloadHandling", EnableCompletedDownloadHandling);
            writer.WriteIntValue("id", Id);
        }
    }
}
#pragma warning restore CS0618
