// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EpisodeResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The absoluteEpisodeNumber property</summary>
        public int? AbsoluteEpisodeNumber { get; set; }
        /// <summary>The airDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AirDate { get; set; }
#nullable restore
#else
        public string AirDate { get; set; }
#endif
        /// <summary>The airDateUtc property</summary>
        public DateTimeOffset? AirDateUtc { get; set; }
        /// <summary>The endTime property</summary>
        public DateTimeOffset? EndTime { get; set; }
        /// <summary>The episodeFile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeFileResource? EpisodeFile { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeFileResource EpisodeFile { get; set; }
#endif
        /// <summary>The episodeFileId property</summary>
        public int? EpisodeFileId { get; set; }
        /// <summary>The episodeNumber property</summary>
        public int? EpisodeNumber { get; set; }
        /// <summary>The finaleType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FinaleType { get; set; }
#nullable restore
#else
        public string FinaleType { get; set; }
#endif
        /// <summary>The grabDate property</summary>
        public DateTimeOffset? GrabDate { get; set; }
        /// <summary>The hasFile property</summary>
        public bool? HasFile { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.MediaCover>? Images { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.MediaCover> Images { get; set; }
#endif
        /// <summary>The lastSearchTime property</summary>
        public DateTimeOffset? LastSearchTime { get; set; }
        /// <summary>The monitored property</summary>
        public bool? Monitored { get; set; }
        /// <summary>The overview property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Overview { get; set; }
#nullable restore
#else
        public string Overview { get; set; }
#endif
        /// <summary>The runtime property</summary>
        public int? Runtime { get; set; }
        /// <summary>The sceneAbsoluteEpisodeNumber property</summary>
        public int? SceneAbsoluteEpisodeNumber { get; set; }
        /// <summary>The sceneEpisodeNumber property</summary>
        public int? SceneEpisodeNumber { get; set; }
        /// <summary>The sceneSeasonNumber property</summary>
        public int? SceneSeasonNumber { get; set; }
        /// <summary>The seasonNumber property</summary>
        public int? SeasonNumber { get; set; }
        /// <summary>The series property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.SeriesResource? Series { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.SeriesResource Series { get; set; }
#endif
        /// <summary>The seriesId property</summary>
        public int? SeriesId { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The tvdbId property</summary>
        public int? TvdbId { get; set; }
        /// <summary>The unverifiedSceneNumbering property</summary>
        public bool? UnverifiedSceneNumbering { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "absoluteEpisodeNumber", n => { AbsoluteEpisodeNumber = n.GetIntValue(); } },
                { "airDate", n => { AirDate = n.GetStringValue(); } },
                { "airDateUtc", n => { AirDateUtc = n.GetDateTimeOffsetValue(); } },
                { "endTime", n => { EndTime = n.GetDateTimeOffsetValue(); } },
                { "episodeFile", n => { EpisodeFile = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeFileResource>(global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeFileResource.CreateFromDiscriminatorValue); } },
                { "episodeFileId", n => { EpisodeFileId = n.GetIntValue(); } },
                { "episodeNumber", n => { EpisodeNumber = n.GetIntValue(); } },
                { "finaleType", n => { FinaleType = n.GetStringValue(); } },
                { "grabDate", n => { GrabDate = n.GetDateTimeOffsetValue(); } },
                { "hasFile", n => { HasFile = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.MediaCover>(global::Soenneker.Sonarr.OpenApiClient.Models.MediaCover.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lastSearchTime", n => { LastSearchTime = n.GetDateTimeOffsetValue(); } },
                { "monitored", n => { Monitored = n.GetBoolValue(); } },
                { "overview", n => { Overview = n.GetStringValue(); } },
                { "runtime", n => { Runtime = n.GetIntValue(); } },
                { "sceneAbsoluteEpisodeNumber", n => { SceneAbsoluteEpisodeNumber = n.GetIntValue(); } },
                { "sceneEpisodeNumber", n => { SceneEpisodeNumber = n.GetIntValue(); } },
                { "sceneSeasonNumber", n => { SceneSeasonNumber = n.GetIntValue(); } },
                { "seasonNumber", n => { SeasonNumber = n.GetIntValue(); } },
                { "series", n => { Series = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesResource>(global::Soenneker.Sonarr.OpenApiClient.Models.SeriesResource.CreateFromDiscriminatorValue); } },
                { "seriesId", n => { SeriesId = n.GetIntValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "tvdbId", n => { TvdbId = n.GetIntValue(); } },
                { "unverifiedSceneNumbering", n => { UnverifiedSceneNumbering = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("absoluteEpisodeNumber", AbsoluteEpisodeNumber);
            writer.WriteStringValue("airDate", AirDate);
            writer.WriteDateTimeOffsetValue("airDateUtc", AirDateUtc);
            writer.WriteDateTimeOffsetValue("endTime", EndTime);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeFileResource>("episodeFile", EpisodeFile);
            writer.WriteIntValue("episodeFileId", EpisodeFileId);
            writer.WriteIntValue("episodeNumber", EpisodeNumber);
            writer.WriteStringValue("finaleType", FinaleType);
            writer.WriteDateTimeOffsetValue("grabDate", GrabDate);
            writer.WriteBoolValue("hasFile", HasFile);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.MediaCover>("images", Images);
            writer.WriteDateTimeOffsetValue("lastSearchTime", LastSearchTime);
            writer.WriteBoolValue("monitored", Monitored);
            writer.WriteStringValue("overview", Overview);
            writer.WriteIntValue("runtime", Runtime);
            writer.WriteIntValue("sceneAbsoluteEpisodeNumber", SceneAbsoluteEpisodeNumber);
            writer.WriteIntValue("sceneEpisodeNumber", SceneEpisodeNumber);
            writer.WriteIntValue("sceneSeasonNumber", SceneSeasonNumber);
            writer.WriteIntValue("seasonNumber", SeasonNumber);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesResource>("series", Series);
            writer.WriteIntValue("seriesId", SeriesId);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("tvdbId", TvdbId);
            writer.WriteBoolValue("unverifiedSceneNumbering", UnverifiedSceneNumbering);
        }
    }
}
#pragma warning restore CS0618
