// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EpisodeHistoryEventType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "grabbed")]
        #pragma warning disable CS1591
        Grabbed,
        #pragma warning restore CS1591
        [EnumMember(Value = "seriesFolderImported")]
        #pragma warning disable CS1591
        SeriesFolderImported,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloadFolderImported")]
        #pragma warning disable CS1591
        DownloadFolderImported,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloadFailed")]
        #pragma warning disable CS1591
        DownloadFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "episodeFileDeleted")]
        #pragma warning disable CS1591
        EpisodeFileDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "episodeFileRenamed")]
        #pragma warning disable CS1591
        EpisodeFileRenamed,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloadIgnored")]
        #pragma warning disable CS1591
        DownloadIgnored,
        #pragma warning restore CS1591
    }
}
