// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Field : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The advanced property</summary>
        public bool? Advanced { get; set; }
        /// <summary>The helpLink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HelpLink { get; set; }
#nullable restore
#else
        public string HelpLink { get; set; }
#endif
        /// <summary>The helpText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HelpText { get; set; }
#nullable restore
#else
        public string HelpText { get; set; }
#endif
        /// <summary>The helpTextWarning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HelpTextWarning { get; set; }
#nullable restore
#else
        public string HelpTextWarning { get; set; }
#endif
        /// <summary>The hidden property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hidden { get; set; }
#nullable restore
#else
        public string Hidden { get; set; }
#endif
        /// <summary>The isFloat property</summary>
        public bool? IsFloat { get; set; }
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The order property</summary>
        public int? Order { get; set; }
        /// <summary>The placeholder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Placeholder { get; set; }
#nullable restore
#else
        public string Placeholder { get; set; }
#endif
        /// <summary>The privacy property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.PrivacyLevel? Privacy { get; set; }
        /// <summary>The section property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Section { get; set; }
#nullable restore
#else
        public string Section { get; set; }
#endif
        /// <summary>The selectOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.SelectOption>? SelectOptions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.SelectOption> SelectOptions { get; set; }
#endif
        /// <summary>The selectOptionsProviderAction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelectOptionsProviderAction { get; set; }
#nullable restore
#else
        public string SelectOptionsProviderAction { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The unit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Unit { get; set; }
#nullable restore
#else
        public string Unit { get; set; }
#endif
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Value { get; set; }
#nullable restore
#else
        public UntypedNode Value { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.Field"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.Field CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.Field();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "advanced", n => { Advanced = n.GetBoolValue(); } },
                { "helpLink", n => { HelpLink = n.GetStringValue(); } },
                { "helpText", n => { HelpText = n.GetStringValue(); } },
                { "helpTextWarning", n => { HelpTextWarning = n.GetStringValue(); } },
                { "hidden", n => { Hidden = n.GetStringValue(); } },
                { "isFloat", n => { IsFloat = n.GetBoolValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "order", n => { Order = n.GetIntValue(); } },
                { "placeholder", n => { Placeholder = n.GetStringValue(); } },
                { "privacy", n => { Privacy = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.PrivacyLevel>(); } },
                { "section", n => { Section = n.GetStringValue(); } },
                { "selectOptions", n => { SelectOptions = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.SelectOption>(global::Soenneker.Sonarr.OpenApiClient.Models.SelectOption.CreateFromDiscriminatorValue)?.AsList(); } },
                { "selectOptionsProviderAction", n => { SelectOptionsProviderAction = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "unit", n => { Unit = n.GetStringValue(); } },
                { "value", n => { Value = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("advanced", Advanced);
            writer.WriteStringValue("helpLink", HelpLink);
            writer.WriteStringValue("helpText", HelpText);
            writer.WriteStringValue("helpTextWarning", HelpTextWarning);
            writer.WriteStringValue("hidden", Hidden);
            writer.WriteBoolValue("isFloat", IsFloat);
            writer.WriteStringValue("label", Label);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("order", Order);
            writer.WriteStringValue("placeholder", Placeholder);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.PrivacyLevel>("privacy", Privacy);
            writer.WriteStringValue("section", Section);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.SelectOption>("selectOptions", SelectOptions);
            writer.WriteStringValue("selectOptionsProviderAction", SelectOptionsProviderAction);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("unit", Unit);
            writer.WriteObjectValue<UntypedNode>("value", Value);
        }
    }
}
#pragma warning restore CS0618
