// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FileDateType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "localAirDate")]
        #pragma warning disable CS1591
        LocalAirDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "utcAirDate")]
        #pragma warning disable CS1591
        UtcAirDate,
        #pragma warning restore CS1591
    }
}
