// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class HealthResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.HealthCheckResult? Type { get; set; }
        /// <summary>The wikiUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.HttpUri? WikiUrl { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.HttpUri WikiUrl { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.HealthResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.HealthResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.HealthResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetIntValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.HealthCheckResult>(); } },
                { "wikiUrl", n => { WikiUrl = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.HttpUri>(global::Soenneker.Sonarr.OpenApiClient.Models.HttpUri.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("source", Source);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.HealthCheckResult>("type", Type);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.HttpUri>("wikiUrl", WikiUrl);
        }
    }
}
#pragma warning restore CS0618
