// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ImportListExclusionResourcePagingResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The page property</summary>
        public int? Page { get; set; }
        /// <summary>The pageSize property</summary>
        public int? PageSize { get; set; }
        /// <summary>The records property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.ImportListExclusionResource>? Records { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.ImportListExclusionResource> Records { get; set; }
#endif
        /// <summary>The sortDirection property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.SortDirection? SortDirection { get; set; }
        /// <summary>The sortKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SortKey { get; set; }
#nullable restore
#else
        public string SortKey { get; set; }
#endif
        /// <summary>The totalRecords property</summary>
        public int? TotalRecords { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.ImportListExclusionResourcePagingResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.ImportListExclusionResourcePagingResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.ImportListExclusionResourcePagingResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "page", n => { Page = n.GetIntValue(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "records", n => { Records = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.ImportListExclusionResource>(global::Soenneker.Sonarr.OpenApiClient.Models.ImportListExclusionResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sortDirection", n => { SortDirection = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.SortDirection>(); } },
                { "sortKey", n => { SortKey = n.GetStringValue(); } },
                { "totalRecords", n => { TotalRecords = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("page", Page);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.ImportListExclusionResource>("records", Records);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.SortDirection>("sortDirection", SortDirection);
            writer.WriteStringValue("sortKey", SortKey);
            writer.WriteIntValue("totalRecords", TotalRecords);
        }
    }
}
#pragma warning restore CS0618
