// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IndexerResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The configContract property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConfigContract { get; set; }
#nullable restore
#else
        public string ConfigContract { get; set; }
#endif
        /// <summary>The downloadClientId property</summary>
        public int? DownloadClientId { get; set; }
        /// <summary>The enableAutomaticSearch property</summary>
        public bool? EnableAutomaticSearch { get; set; }
        /// <summary>The enableInteractiveSearch property</summary>
        public bool? EnableInteractiveSearch { get; set; }
        /// <summary>The enableRss property</summary>
        public bool? EnableRss { get; set; }
        /// <summary>The fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.Field>? Fields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.Field> Fields { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The implementation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Implementation { get; set; }
#nullable restore
#else
        public string Implementation { get; set; }
#endif
        /// <summary>The implementationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImplementationName { get; set; }
#nullable restore
#else
        public string ImplementationName { get; set; }
#endif
        /// <summary>The infoLink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InfoLink { get; set; }
#nullable restore
#else
        public string InfoLink { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.ProviderMessage? Message { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.ProviderMessage Message { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The presets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource>? Presets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource> Presets { get; set; }
#endif
        /// <summary>The priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The protocol property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.DownloadProtocol? Protocol { get; set; }
        /// <summary>The seasonSearchMaximumSingleEpisodeAge property</summary>
        public int? SeasonSearchMaximumSingleEpisodeAge { get; set; }
        /// <summary>The supportsRss property</summary>
        public bool? SupportsRss { get; set; }
        /// <summary>The supportsSearch property</summary>
        public bool? SupportsSearch { get; set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Tags { get; set; }
#nullable restore
#else
        public List<int?> Tags { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "configContract", n => { ConfigContract = n.GetStringValue(); } },
                { "downloadClientId", n => { DownloadClientId = n.GetIntValue(); } },
                { "enableAutomaticSearch", n => { EnableAutomaticSearch = n.GetBoolValue(); } },
                { "enableInteractiveSearch", n => { EnableInteractiveSearch = n.GetBoolValue(); } },
                { "enableRss", n => { EnableRss = n.GetBoolValue(); } },
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.Field>(global::Soenneker.Sonarr.OpenApiClient.Models.Field.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "implementation", n => { Implementation = n.GetStringValue(); } },
                { "implementationName", n => { ImplementationName = n.GetStringValue(); } },
                { "infoLink", n => { InfoLink = n.GetStringValue(); } },
                { "message", n => { Message = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.ProviderMessage>(global::Soenneker.Sonarr.OpenApiClient.Models.ProviderMessage.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "presets", n => { Presets = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource>(global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "protocol", n => { Protocol = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.DownloadProtocol>(); } },
                { "seasonSearchMaximumSingleEpisodeAge", n => { SeasonSearchMaximumSingleEpisodeAge = n.GetIntValue(); } },
                { "supportsRss", n => { SupportsRss = n.GetBoolValue(); } },
                { "supportsSearch", n => { SupportsSearch = n.GetBoolValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("configContract", ConfigContract);
            writer.WriteIntValue("downloadClientId", DownloadClientId);
            writer.WriteBoolValue("enableAutomaticSearch", EnableAutomaticSearch);
            writer.WriteBoolValue("enableInteractiveSearch", EnableInteractiveSearch);
            writer.WriteBoolValue("enableRss", EnableRss);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.Field>("fields", Fields);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("implementation", Implementation);
            writer.WriteStringValue("implementationName", ImplementationName);
            writer.WriteStringValue("infoLink", InfoLink);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.ProviderMessage>("message", Message);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource>("presets", Presets);
            writer.WriteIntValue("priority", Priority);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.DownloadProtocol>("protocol", Protocol);
            writer.WriteIntValue("seasonSearchMaximumSingleEpisodeAge", SeasonSearchMaximumSingleEpisodeAge);
            writer.WriteBoolValue("supportsRss", SupportsRss);
            writer.WriteBoolValue("supportsSearch", SupportsSearch);
            writer.WriteCollectionOfPrimitiveValues<int?>("tags", Tags);
        }
    }
}
#pragma warning restore CS0618
