// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ManualImportReprocessResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customFormats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatResource>? CustomFormats { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatResource> CustomFormats { get; set; }
#endif
        /// <summary>The customFormatScore property</summary>
        public int? CustomFormatScore { get; set; }
        /// <summary>The downloadId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DownloadId { get; set; }
#nullable restore
#else
        public string DownloadId { get; set; }
#endif
        /// <summary>The episodeIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? EpisodeIds { get; set; }
#nullable restore
#else
        public List<int?> EpisodeIds { get; set; }
#endif
        /// <summary>The episodes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResource>? Episodes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResource> Episodes { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The indexerFlags property</summary>
        public int? IndexerFlags { get; set; }
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.Language>? Languages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.Language> Languages { get; set; }
#endif
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.QualityModel? Quality { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.QualityModel Quality { get; set; }
#endif
        /// <summary>The rejections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.ImportRejectionResource>? Rejections { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.ImportRejectionResource> Rejections { get; set; }
#endif
        /// <summary>The releaseGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseGroup { get; set; }
#nullable restore
#else
        public string ReleaseGroup { get; set; }
#endif
        /// <summary>The releaseType property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.ReleaseType? ReleaseType { get; set; }
        /// <summary>The seasonNumber property</summary>
        public int? SeasonNumber { get; set; }
        /// <summary>The seriesId property</summary>
        public int? SeriesId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.ManualImportReprocessResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.ManualImportReprocessResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.ManualImportReprocessResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customFormatScore", n => { CustomFormatScore = n.GetIntValue(); } },
                { "customFormats", n => { CustomFormats = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatResource>(global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "downloadId", n => { DownloadId = n.GetStringValue(); } },
                { "episodeIds", n => { EpisodeIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "episodes", n => { Episodes = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResource>(global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "indexerFlags", n => { IndexerFlags = n.GetIntValue(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.Language>(global::Soenneker.Sonarr.OpenApiClient.Models.Language.CreateFromDiscriminatorValue)?.AsList(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.QualityModel>(global::Soenneker.Sonarr.OpenApiClient.Models.QualityModel.CreateFromDiscriminatorValue); } },
                { "rejections", n => { Rejections = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.ImportRejectionResource>(global::Soenneker.Sonarr.OpenApiClient.Models.ImportRejectionResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "releaseGroup", n => { ReleaseGroup = n.GetStringValue(); } },
                { "releaseType", n => { ReleaseType = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.ReleaseType>(); } },
                { "seasonNumber", n => { SeasonNumber = n.GetIntValue(); } },
                { "seriesId", n => { SeriesId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.CustomFormatResource>("customFormats", CustomFormats);
            writer.WriteIntValue("customFormatScore", CustomFormatScore);
            writer.WriteStringValue("downloadId", DownloadId);
            writer.WriteCollectionOfPrimitiveValues<int?>("episodeIds", EpisodeIds);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.EpisodeResource>("episodes", Episodes);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("indexerFlags", IndexerFlags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.Language>("languages", Languages);
            writer.WriteStringValue("path", Path);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.QualityModel>("quality", Quality);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.ImportRejectionResource>("rejections", Rejections);
            writer.WriteStringValue("releaseGroup", ReleaseGroup);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.ReleaseType>("releaseType", ReleaseType);
            writer.WriteIntValue("seasonNumber", SeasonNumber);
            writer.WriteIntValue("seriesId", SeriesId);
        }
    }
}
#pragma warning restore CS0618
