// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MediaCoverTypes
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "poster")]
        #pragma warning disable CS1591
        Poster,
        #pragma warning restore CS1591
        [EnumMember(Value = "banner")]
        #pragma warning disable CS1591
        Banner,
        #pragma warning restore CS1591
        [EnumMember(Value = "fanart")]
        #pragma warning disable CS1591
        Fanart,
        #pragma warning restore CS1591
        [EnumMember(Value = "screenshot")]
        #pragma warning disable CS1591
        Screenshot,
        #pragma warning restore CS1591
        [EnumMember(Value = "headshot")]
        #pragma warning disable CS1591
        Headshot,
        #pragma warning restore CS1591
        [EnumMember(Value = "clearlogo")]
        #pragma warning disable CS1591
        Clearlogo,
        #pragma warning restore CS1591
    }
}
