// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NamingConfigResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The animeEpisodeFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnimeEpisodeFormat { get; set; }
#nullable restore
#else
        public string AnimeEpisodeFormat { get; set; }
#endif
        /// <summary>The colonReplacementFormat property</summary>
        public int? ColonReplacementFormat { get; set; }
        /// <summary>The customColonReplacementFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomColonReplacementFormat { get; set; }
#nullable restore
#else
        public string CustomColonReplacementFormat { get; set; }
#endif
        /// <summary>The dailyEpisodeFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DailyEpisodeFormat { get; set; }
#nullable restore
#else
        public string DailyEpisodeFormat { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The multiEpisodeStyle property</summary>
        public int? MultiEpisodeStyle { get; set; }
        /// <summary>The renameEpisodes property</summary>
        public bool? RenameEpisodes { get; set; }
        /// <summary>The replaceIllegalCharacters property</summary>
        public bool? ReplaceIllegalCharacters { get; set; }
        /// <summary>The seasonFolderFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeasonFolderFormat { get; set; }
#nullable restore
#else
        public string SeasonFolderFormat { get; set; }
#endif
        /// <summary>The seriesFolderFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesFolderFormat { get; set; }
#nullable restore
#else
        public string SeriesFolderFormat { get; set; }
#endif
        /// <summary>The specialsFolderFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpecialsFolderFormat { get; set; }
#nullable restore
#else
        public string SpecialsFolderFormat { get; set; }
#endif
        /// <summary>The standardEpisodeFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StandardEpisodeFormat { get; set; }
#nullable restore
#else
        public string StandardEpisodeFormat { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.NamingConfigResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.NamingConfigResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.NamingConfigResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "animeEpisodeFormat", n => { AnimeEpisodeFormat = n.GetStringValue(); } },
                { "colonReplacementFormat", n => { ColonReplacementFormat = n.GetIntValue(); } },
                { "customColonReplacementFormat", n => { CustomColonReplacementFormat = n.GetStringValue(); } },
                { "dailyEpisodeFormat", n => { DailyEpisodeFormat = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "multiEpisodeStyle", n => { MultiEpisodeStyle = n.GetIntValue(); } },
                { "renameEpisodes", n => { RenameEpisodes = n.GetBoolValue(); } },
                { "replaceIllegalCharacters", n => { ReplaceIllegalCharacters = n.GetBoolValue(); } },
                { "seasonFolderFormat", n => { SeasonFolderFormat = n.GetStringValue(); } },
                { "seriesFolderFormat", n => { SeriesFolderFormat = n.GetStringValue(); } },
                { "specialsFolderFormat", n => { SpecialsFolderFormat = n.GetStringValue(); } },
                { "standardEpisodeFormat", n => { StandardEpisodeFormat = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("animeEpisodeFormat", AnimeEpisodeFormat);
            writer.WriteIntValue("colonReplacementFormat", ColonReplacementFormat);
            writer.WriteStringValue("customColonReplacementFormat", CustomColonReplacementFormat);
            writer.WriteStringValue("dailyEpisodeFormat", DailyEpisodeFormat);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("multiEpisodeStyle", MultiEpisodeStyle);
            writer.WriteBoolValue("renameEpisodes", RenameEpisodes);
            writer.WriteBoolValue("replaceIllegalCharacters", ReplaceIllegalCharacters);
            writer.WriteStringValue("seasonFolderFormat", SeasonFolderFormat);
            writer.WriteStringValue("seriesFolderFormat", SeriesFolderFormat);
            writer.WriteStringValue("specialsFolderFormat", SpecialsFolderFormat);
            writer.WriteStringValue("standardEpisodeFormat", StandardEpisodeFormat);
        }
    }
}
#pragma warning restore CS0618
