// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ParsedEpisodeInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The absoluteEpisodeNumbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AbsoluteEpisodeNumbers { get; set; }
#nullable restore
#else
        public List<int?> AbsoluteEpisodeNumbers { get; set; }
#endif
        /// <summary>The airDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AirDate { get; set; }
#nullable restore
#else
        public string AirDate { get; set; }
#endif
        /// <summary>The dailyPart property</summary>
        public int? DailyPart { get; set; }
        /// <summary>The episodeNumbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? EpisodeNumbers { get; set; }
#nullable restore
#else
        public List<int?> EpisodeNumbers { get; set; }
#endif
        /// <summary>The fullSeason property</summary>
        public bool? FullSeason { get; set; }
        /// <summary>The isAbsoluteNumbering property</summary>
        public bool? IsAbsoluteNumbering { get; private set; }
        /// <summary>The isDaily property</summary>
        public bool? IsDaily { get; private set; }
        /// <summary>The isMiniSeries property</summary>
        public bool? IsMiniSeries { get; set; }
        /// <summary>The isMultiSeason property</summary>
        public bool? IsMultiSeason { get; set; }
        /// <summary>The isPartialSeason property</summary>
        public bool? IsPartialSeason { get; set; }
        /// <summary>The isPossibleSceneSeasonSpecial property</summary>
        public bool? IsPossibleSceneSeasonSpecial { get; private set; }
        /// <summary>The isPossibleSpecialEpisode property</summary>
        public bool? IsPossibleSpecialEpisode { get; private set; }
        /// <summary>The isSeasonExtra property</summary>
        public bool? IsSeasonExtra { get; set; }
        /// <summary>The isSplitEpisode property</summary>
        public bool? IsSplitEpisode { get; set; }
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.Language>? Languages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.Language> Languages { get; set; }
#endif
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.QualityModel? Quality { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.QualityModel Quality { get; set; }
#endif
        /// <summary>The releaseGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseGroup { get; set; }
#nullable restore
#else
        public string ReleaseGroup { get; set; }
#endif
        /// <summary>The releaseHash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseHash { get; set; }
#nullable restore
#else
        public string ReleaseHash { get; set; }
#endif
        /// <summary>The releaseTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseTitle { get; set; }
#nullable restore
#else
        public string ReleaseTitle { get; set; }
#endif
        /// <summary>The releaseTokens property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseTokens { get; set; }
#nullable restore
#else
        public string ReleaseTokens { get; set; }
#endif
        /// <summary>The releaseType property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.ReleaseType? ReleaseType { get; set; }
        /// <summary>The seasonNumber property</summary>
        public int? SeasonNumber { get; set; }
        /// <summary>The seasonPart property</summary>
        public int? SeasonPart { get; set; }
        /// <summary>The seriesTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesTitle { get; set; }
#nullable restore
#else
        public string SeriesTitle { get; set; }
#endif
        /// <summary>The seriesTitleInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.SeriesTitleInfo? SeriesTitleInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.SeriesTitleInfo SeriesTitleInfo { get; set; }
#endif
        /// <summary>The special property</summary>
        public bool? Special { get; set; }
        /// <summary>The specialAbsoluteEpisodeNumbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? SpecialAbsoluteEpisodeNumbers { get; set; }
#nullable restore
#else
        public List<double?> SpecialAbsoluteEpisodeNumbers { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.ParsedEpisodeInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.ParsedEpisodeInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.ParsedEpisodeInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "absoluteEpisodeNumbers", n => { AbsoluteEpisodeNumbers = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "airDate", n => { AirDate = n.GetStringValue(); } },
                { "dailyPart", n => { DailyPart = n.GetIntValue(); } },
                { "episodeNumbers", n => { EpisodeNumbers = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "fullSeason", n => { FullSeason = n.GetBoolValue(); } },
                { "isAbsoluteNumbering", n => { IsAbsoluteNumbering = n.GetBoolValue(); } },
                { "isDaily", n => { IsDaily = n.GetBoolValue(); } },
                { "isMiniSeries", n => { IsMiniSeries = n.GetBoolValue(); } },
                { "isMultiSeason", n => { IsMultiSeason = n.GetBoolValue(); } },
                { "isPartialSeason", n => { IsPartialSeason = n.GetBoolValue(); } },
                { "isPossibleSceneSeasonSpecial", n => { IsPossibleSceneSeasonSpecial = n.GetBoolValue(); } },
                { "isPossibleSpecialEpisode", n => { IsPossibleSpecialEpisode = n.GetBoolValue(); } },
                { "isSeasonExtra", n => { IsSeasonExtra = n.GetBoolValue(); } },
                { "isSplitEpisode", n => { IsSplitEpisode = n.GetBoolValue(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.Language>(global::Soenneker.Sonarr.OpenApiClient.Models.Language.CreateFromDiscriminatorValue)?.AsList(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.QualityModel>(global::Soenneker.Sonarr.OpenApiClient.Models.QualityModel.CreateFromDiscriminatorValue); } },
                { "releaseGroup", n => { ReleaseGroup = n.GetStringValue(); } },
                { "releaseHash", n => { ReleaseHash = n.GetStringValue(); } },
                { "releaseTitle", n => { ReleaseTitle = n.GetStringValue(); } },
                { "releaseTokens", n => { ReleaseTokens = n.GetStringValue(); } },
                { "releaseType", n => { ReleaseType = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.ReleaseType>(); } },
                { "seasonNumber", n => { SeasonNumber = n.GetIntValue(); } },
                { "seasonPart", n => { SeasonPart = n.GetIntValue(); } },
                { "seriesTitle", n => { SeriesTitle = n.GetStringValue(); } },
                { "seriesTitleInfo", n => { SeriesTitleInfo = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesTitleInfo>(global::Soenneker.Sonarr.OpenApiClient.Models.SeriesTitleInfo.CreateFromDiscriminatorValue); } },
                { "special", n => { Special = n.GetBoolValue(); } },
                { "specialAbsoluteEpisodeNumbers", n => { SpecialAbsoluteEpisodeNumbers = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("absoluteEpisodeNumbers", AbsoluteEpisodeNumbers);
            writer.WriteStringValue("airDate", AirDate);
            writer.WriteIntValue("dailyPart", DailyPart);
            writer.WriteCollectionOfPrimitiveValues<int?>("episodeNumbers", EpisodeNumbers);
            writer.WriteBoolValue("fullSeason", FullSeason);
            writer.WriteBoolValue("isMiniSeries", IsMiniSeries);
            writer.WriteBoolValue("isMultiSeason", IsMultiSeason);
            writer.WriteBoolValue("isPartialSeason", IsPartialSeason);
            writer.WriteBoolValue("isSeasonExtra", IsSeasonExtra);
            writer.WriteBoolValue("isSplitEpisode", IsSplitEpisode);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.Language>("languages", Languages);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.QualityModel>("quality", Quality);
            writer.WriteStringValue("releaseGroup", ReleaseGroup);
            writer.WriteStringValue("releaseHash", ReleaseHash);
            writer.WriteStringValue("releaseTitle", ReleaseTitle);
            writer.WriteStringValue("releaseTokens", ReleaseTokens);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.ReleaseType>("releaseType", ReleaseType);
            writer.WriteIntValue("seasonNumber", SeasonNumber);
            writer.WriteIntValue("seasonPart", SeasonPart);
            writer.WriteStringValue("seriesTitle", SeriesTitle);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesTitleInfo>("seriesTitleInfo", SeriesTitleInfo);
            writer.WriteBoolValue("special", Special);
            writer.WriteCollectionOfPrimitiveValues<double?>("specialAbsoluteEpisodeNumbers", SpecialAbsoluteEpisodeNumbers);
        }
    }
}
#pragma warning restore CS0618
