// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PrivacyLevel
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "normal")]
        #pragma warning disable CS1591
        Normal,
        #pragma warning restore CS1591
        [EnumMember(Value = "password")]
        #pragma warning disable CS1591
        Password,
        #pragma warning restore CS1591
        [EnumMember(Value = "apiKey")]
        #pragma warning disable CS1591
        ApiKey,
        #pragma warning restore CS1591
        [EnumMember(Value = "userName")]
        #pragma warning disable CS1591
        UserName,
        #pragma warning restore CS1591
    }
}
