// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProperDownloadTypes
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "preferAndUpgrade")]
        #pragma warning disable CS1591
        PreferAndUpgrade,
        #pragma warning restore CS1591
        [EnumMember(Value = "doNotUpgrade")]
        #pragma warning disable CS1591
        DoNotUpgrade,
        #pragma warning restore CS1591
        [EnumMember(Value = "doNotPrefer")]
        #pragma warning disable CS1591
        DoNotPrefer,
        #pragma warning restore CS1591
    }
}
