// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProxyType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "http")]
        #pragma warning disable CS1591
        Http,
        #pragma warning restore CS1591
        [EnumMember(Value = "socks4")]
        #pragma warning disable CS1591
        Socks4,
        #pragma warning restore CS1591
        [EnumMember(Value = "socks5")]
        #pragma warning disable CS1591
        Socks5,
        #pragma warning restore CS1591
    }
}
