// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum QualitySource
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "television")]
        #pragma warning disable CS1591
        Television,
        #pragma warning restore CS1591
        [EnumMember(Value = "televisionRaw")]
        #pragma warning disable CS1591
        TelevisionRaw,
        #pragma warning restore CS1591
        [EnumMember(Value = "web")]
        #pragma warning disable CS1591
        Web,
        #pragma warning restore CS1591
        [EnumMember(Value = "webRip")]
        #pragma warning disable CS1591
        WebRip,
        #pragma warning restore CS1591
        [EnumMember(Value = "dvd")]
        #pragma warning disable CS1591
        Dvd,
        #pragma warning restore CS1591
        [EnumMember(Value = "bluray")]
        #pragma warning disable CS1591
        Bluray,
        #pragma warning restore CS1591
        [EnumMember(Value = "blurayRaw")]
        #pragma warning disable CS1591
        BlurayRaw,
        #pragma warning restore CS1591
    }
}
