// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QualityDefinitionResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The maxSize property</summary>
        public double? MaxSize { get; set; }
        /// <summary>The minSize property</summary>
        public double? MinSize { get; set; }
        /// <summary>The preferredSize property</summary>
        public double? PreferredSize { get; set; }
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.Quality? Quality { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.Quality Quality { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The weight property</summary>
        public int? Weight { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.QualityDefinitionResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.QualityDefinitionResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.QualityDefinitionResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetIntValue(); } },
                { "maxSize", n => { MaxSize = n.GetDoubleValue(); } },
                { "minSize", n => { MinSize = n.GetDoubleValue(); } },
                { "preferredSize", n => { PreferredSize = n.GetDoubleValue(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.Quality>(global::Soenneker.Sonarr.OpenApiClient.Models.Quality.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "weight", n => { Weight = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("id", Id);
            writer.WriteDoubleValue("maxSize", MaxSize);
            writer.WriteDoubleValue("minSize", MinSize);
            writer.WriteDoubleValue("preferredSize", PreferredSize);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.Quality>("quality", Quality);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("weight", Weight);
        }
    }
}
#pragma warning restore CS0618
