// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QualityProfileQualityItemResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The allowed property</summary>
        public bool? Allowed { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.QualityProfileQualityItemResource>? Items { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.QualityProfileQualityItemResource> Items { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.Quality? Quality { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.Quality Quality { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.QualityProfileQualityItemResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.QualityProfileQualityItemResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.QualityProfileQualityItemResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowed", n => { Allowed = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.QualityProfileQualityItemResource>(global::Soenneker.Sonarr.OpenApiClient.Models.QualityProfileQualityItemResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.Quality>(global::Soenneker.Sonarr.OpenApiClient.Models.Quality.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowed", Allowed);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.QualityProfileQualityItemResource>("items", Items);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.Quality>("quality", Quality);
        }
    }
}
#pragma warning restore CS0618
