// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum QueueStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "queued")]
        #pragma warning disable CS1591
        Queued,
        #pragma warning restore CS1591
        [EnumMember(Value = "paused")]
        #pragma warning disable CS1591
        Paused,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloading")]
        #pragma warning disable CS1591
        Downloading,
        #pragma warning restore CS1591
        [EnumMember(Value = "completed")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "warning")]
        #pragma warning disable CS1591
        Warning,
        #pragma warning restore CS1591
        [EnumMember(Value = "delay")]
        #pragma warning disable CS1591
        Delay,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloadClientUnavailable")]
        #pragma warning disable CS1591
        DownloadClientUnavailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "fallback")]
        #pragma warning disable CS1591
        Fallback,
        #pragma warning restore CS1591
    }
}
