// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RejectionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "permanent")]
        #pragma warning disable CS1591
        Permanent,
        #pragma warning restore CS1591
        [EnumMember(Value = "temporary")]
        #pragma warning disable CS1591
        Temporary,
        #pragma warning restore CS1591
    }
}
