// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ReleaseType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "singleEpisode")]
        #pragma warning disable CS1591
        SingleEpisode,
        #pragma warning restore CS1591
        [EnumMember(Value = "multiEpisode")]
        #pragma warning disable CS1591
        MultiEpisode,
        #pragma warning restore CS1591
        [EnumMember(Value = "seasonPack")]
        #pragma warning disable CS1591
        SeasonPack,
        #pragma warning restore CS1591
    }
}
