// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReleaseEpisodeResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The absoluteEpisodeNumber property</summary>
        public int? AbsoluteEpisodeNumber { get; set; }
        /// <summary>The episodeNumber property</summary>
        public int? EpisodeNumber { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The seasonNumber property</summary>
        public int? SeasonNumber { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.ReleaseEpisodeResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.ReleaseEpisodeResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.ReleaseEpisodeResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "absoluteEpisodeNumber", n => { AbsoluteEpisodeNumber = n.GetIntValue(); } },
                { "episodeNumber", n => { EpisodeNumber = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "seasonNumber", n => { SeasonNumber = n.GetIntValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("absoluteEpisodeNumber", AbsoluteEpisodeNumber);
            writer.WriteIntValue("episodeNumber", EpisodeNumber);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("seasonNumber", SeasonNumber);
            writer.WriteStringValue("title", Title);
        }
    }
}
#pragma warning restore CS0618
