// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RescanAfterRefreshType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "always")]
        #pragma warning disable CS1591
        Always,
        #pragma warning restore CS1591
        [EnumMember(Value = "afterManual")]
        #pragma warning disable CS1591
        AfterManual,
        #pragma warning restore CS1591
        [EnumMember(Value = "never")]
        #pragma warning disable CS1591
        Never,
        #pragma warning restore CS1591
    }
}
