// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SeasonStatisticsResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The episodeCount property</summary>
        public int? EpisodeCount { get; set; }
        /// <summary>The episodeFileCount property</summary>
        public int? EpisodeFileCount { get; set; }
        /// <summary>The nextAiring property</summary>
        public DateTimeOffset? NextAiring { get; set; }
        /// <summary>The percentOfEpisodes property</summary>
        public double? PercentOfEpisodes { get; private set; }
        /// <summary>The previousAiring property</summary>
        public DateTimeOffset? PreviousAiring { get; set; }
        /// <summary>The releaseGroups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ReleaseGroups { get; set; }
#nullable restore
#else
        public List<string> ReleaseGroups { get; set; }
#endif
        /// <summary>The sizeOnDisk property</summary>
        public long? SizeOnDisk { get; set; }
        /// <summary>The totalEpisodeCount property</summary>
        public int? TotalEpisodeCount { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.SeasonStatisticsResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.SeasonStatisticsResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.SeasonStatisticsResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "episodeCount", n => { EpisodeCount = n.GetIntValue(); } },
                { "episodeFileCount", n => { EpisodeFileCount = n.GetIntValue(); } },
                { "nextAiring", n => { NextAiring = n.GetDateTimeOffsetValue(); } },
                { "percentOfEpisodes", n => { PercentOfEpisodes = n.GetDoubleValue(); } },
                { "previousAiring", n => { PreviousAiring = n.GetDateTimeOffsetValue(); } },
                { "releaseGroups", n => { ReleaseGroups = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sizeOnDisk", n => { SizeOnDisk = n.GetLongValue(); } },
                { "totalEpisodeCount", n => { TotalEpisodeCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("episodeCount", EpisodeCount);
            writer.WriteIntValue("episodeFileCount", EpisodeFileCount);
            writer.WriteDateTimeOffsetValue("nextAiring", NextAiring);
            writer.WriteDateTimeOffsetValue("previousAiring", PreviousAiring);
            writer.WriteCollectionOfPrimitiveValues<string>("releaseGroups", ReleaseGroups);
            writer.WriteLongValue("sizeOnDisk", SizeOnDisk);
            writer.WriteIntValue("totalEpisodeCount", TotalEpisodeCount);
        }
    }
}
#pragma warning restore CS0618
