// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SeriesStatusType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "continuing")]
        #pragma warning disable CS1591
        Continuing,
        #pragma warning restore CS1591
        [EnumMember(Value = "ended")]
        #pragma warning disable CS1591
        Ended,
        #pragma warning restore CS1591
        [EnumMember(Value = "upcoming")]
        #pragma warning disable CS1591
        Upcoming,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
    }
}
