// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SeriesResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The added property</summary>
        public DateTimeOffset? Added { get; set; }
        /// <summary>The addOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.AddSeriesOptions? AddOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.AddSeriesOptions AddOptions { get; set; }
#endif
        /// <summary>The airTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AirTime { get; set; }
#nullable restore
#else
        public string AirTime { get; set; }
#endif
        /// <summary>The alternateTitles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.AlternateTitleResource>? AlternateTitles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.AlternateTitleResource> AlternateTitles { get; set; }
#endif
        /// <summary>The certification property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Certification { get; set; }
#nullable restore
#else
        public string Certification { get; set; }
#endif
        /// <summary>The cleanTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CleanTitle { get; set; }
#nullable restore
#else
        public string CleanTitle { get; set; }
#endif
        /// <summary>The ended property</summary>
        public bool? Ended { get; private set; }
        /// <summary>The episodesChanged property</summary>
        public bool? EpisodesChanged { get; set; }
        /// <summary>The firstAired property</summary>
        public DateTimeOffset? FirstAired { get; set; }
        /// <summary>The folder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Folder { get; set; }
#nullable restore
#else
        public string Folder { get; set; }
#endif
        /// <summary>The genres property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Genres { get; set; }
#nullable restore
#else
        public List<string> Genres { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.MediaCover>? Images { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.MediaCover> Images { get; set; }
#endif
        /// <summary>The imdbId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImdbId { get; set; }
#nullable restore
#else
        public string ImdbId { get; set; }
#endif
        /// <summary>The languageProfileId property</summary>
        [Obsolete("")]
        public int? LanguageProfileId { get; private set; }
        /// <summary>The lastAired property</summary>
        public DateTimeOffset? LastAired { get; set; }
        /// <summary>The monitored property</summary>
        public bool? Monitored { get; set; }
        /// <summary>The monitorNewItems property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.NewItemMonitorTypes? MonitorNewItems { get; set; }
        /// <summary>The network property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Network { get; set; }
#nullable restore
#else
        public string Network { get; set; }
#endif
        /// <summary>The nextAiring property</summary>
        public DateTimeOffset? NextAiring { get; set; }
        /// <summary>The originalLanguage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.Language? OriginalLanguage { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.Language OriginalLanguage { get; set; }
#endif
        /// <summary>The overview property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Overview { get; set; }
#nullable restore
#else
        public string Overview { get; set; }
#endif
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The previousAiring property</summary>
        public DateTimeOffset? PreviousAiring { get; set; }
        /// <summary>The profileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileName { get; set; }
#nullable restore
#else
        public string ProfileName { get; set; }
#endif
        /// <summary>The qualityProfileId property</summary>
        public int? QualityProfileId { get; set; }
        /// <summary>The ratings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.Ratings? Ratings { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.Ratings Ratings { get; set; }
#endif
        /// <summary>The remotePoster property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemotePoster { get; set; }
#nullable restore
#else
        public string RemotePoster { get; set; }
#endif
        /// <summary>The rootFolderPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootFolderPath { get; set; }
#nullable restore
#else
        public string RootFolderPath { get; set; }
#endif
        /// <summary>The runtime property</summary>
        public int? Runtime { get; set; }
        /// <summary>The seasonFolder property</summary>
        public bool? SeasonFolder { get; set; }
        /// <summary>The seasons property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.SeasonResource>? Seasons { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sonarr.OpenApiClient.Models.SeasonResource> Seasons { get; set; }
#endif
        /// <summary>The seriesType property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.SeriesTypes? SeriesType { get; set; }
        /// <summary>The sortTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SortTitle { get; set; }
#nullable restore
#else
        public string SortTitle { get; set; }
#endif
        /// <summary>The statistics property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.SeriesStatisticsResource? Statistics { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.SeriesStatisticsResource Statistics { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.SeriesStatusType? Status { get; set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Tags { get; set; }
#nullable restore
#else
        public List<int?> Tags { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The titleSlug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TitleSlug { get; set; }
#nullable restore
#else
        public string TitleSlug { get; set; }
#endif
        /// <summary>The tmdbId property</summary>
        public int? TmdbId { get; set; }
        /// <summary>The tvdbId property</summary>
        public int? TvdbId { get; set; }
        /// <summary>The tvMazeId property</summary>
        public int? TvMazeId { get; set; }
        /// <summary>The tvRageId property</summary>
        public int? TvRageId { get; set; }
        /// <summary>The useSceneNumbering property</summary>
        public bool? UseSceneNumbering { get; set; }
        /// <summary>The year property</summary>
        public int? Year { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.SeriesResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.SeriesResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.SeriesResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addOptions", n => { AddOptions = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.AddSeriesOptions>(global::Soenneker.Sonarr.OpenApiClient.Models.AddSeriesOptions.CreateFromDiscriminatorValue); } },
                { "added", n => { Added = n.GetDateTimeOffsetValue(); } },
                { "airTime", n => { AirTime = n.GetStringValue(); } },
                { "alternateTitles", n => { AlternateTitles = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.AlternateTitleResource>(global::Soenneker.Sonarr.OpenApiClient.Models.AlternateTitleResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "certification", n => { Certification = n.GetStringValue(); } },
                { "cleanTitle", n => { CleanTitle = n.GetStringValue(); } },
                { "ended", n => { Ended = n.GetBoolValue(); } },
                { "episodesChanged", n => { EpisodesChanged = n.GetBoolValue(); } },
                { "firstAired", n => { FirstAired = n.GetDateTimeOffsetValue(); } },
                { "folder", n => { Folder = n.GetStringValue(); } },
                { "genres", n => { Genres = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.MediaCover>(global::Soenneker.Sonarr.OpenApiClient.Models.MediaCover.CreateFromDiscriminatorValue)?.AsList(); } },
                { "imdbId", n => { ImdbId = n.GetStringValue(); } },
                { "languageProfileId", n => { LanguageProfileId = n.GetIntValue(); } },
                { "lastAired", n => { LastAired = n.GetDateTimeOffsetValue(); } },
                { "monitorNewItems", n => { MonitorNewItems = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.NewItemMonitorTypes>(); } },
                { "monitored", n => { Monitored = n.GetBoolValue(); } },
                { "network", n => { Network = n.GetStringValue(); } },
                { "nextAiring", n => { NextAiring = n.GetDateTimeOffsetValue(); } },
                { "originalLanguage", n => { OriginalLanguage = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.Language>(global::Soenneker.Sonarr.OpenApiClient.Models.Language.CreateFromDiscriminatorValue); } },
                { "overview", n => { Overview = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "previousAiring", n => { PreviousAiring = n.GetDateTimeOffsetValue(); } },
                { "profileName", n => { ProfileName = n.GetStringValue(); } },
                { "qualityProfileId", n => { QualityProfileId = n.GetIntValue(); } },
                { "ratings", n => { Ratings = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.Ratings>(global::Soenneker.Sonarr.OpenApiClient.Models.Ratings.CreateFromDiscriminatorValue); } },
                { "remotePoster", n => { RemotePoster = n.GetStringValue(); } },
                { "rootFolderPath", n => { RootFolderPath = n.GetStringValue(); } },
                { "runtime", n => { Runtime = n.GetIntValue(); } },
                { "seasonFolder", n => { SeasonFolder = n.GetBoolValue(); } },
                { "seasons", n => { Seasons = n.GetCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.SeasonResource>(global::Soenneker.Sonarr.OpenApiClient.Models.SeasonResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "seriesType", n => { SeriesType = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesTypes>(); } },
                { "sortTitle", n => { SortTitle = n.GetStringValue(); } },
                { "statistics", n => { Statistics = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesStatisticsResource>(global::Soenneker.Sonarr.OpenApiClient.Models.SeriesStatisticsResource.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesStatusType>(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "titleSlug", n => { TitleSlug = n.GetStringValue(); } },
                { "tmdbId", n => { TmdbId = n.GetIntValue(); } },
                { "tvMazeId", n => { TvMazeId = n.GetIntValue(); } },
                { "tvRageId", n => { TvRageId = n.GetIntValue(); } },
                { "tvdbId", n => { TvdbId = n.GetIntValue(); } },
                { "useSceneNumbering", n => { UseSceneNumbering = n.GetBoolValue(); } },
                { "year", n => { Year = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("added", Added);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.AddSeriesOptions>("addOptions", AddOptions);
            writer.WriteStringValue("airTime", AirTime);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.AlternateTitleResource>("alternateTitles", AlternateTitles);
            writer.WriteStringValue("certification", Certification);
            writer.WriteStringValue("cleanTitle", CleanTitle);
            writer.WriteBoolValue("episodesChanged", EpisodesChanged);
            writer.WriteDateTimeOffsetValue("firstAired", FirstAired);
            writer.WriteStringValue("folder", Folder);
            writer.WriteCollectionOfPrimitiveValues<string>("genres", Genres);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.MediaCover>("images", Images);
            writer.WriteStringValue("imdbId", ImdbId);
            writer.WriteDateTimeOffsetValue("lastAired", LastAired);
            writer.WriteBoolValue("monitored", Monitored);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.NewItemMonitorTypes>("monitorNewItems", MonitorNewItems);
            writer.WriteStringValue("network", Network);
            writer.WriteDateTimeOffsetValue("nextAiring", NextAiring);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.Language>("originalLanguage", OriginalLanguage);
            writer.WriteStringValue("overview", Overview);
            writer.WriteStringValue("path", Path);
            writer.WriteDateTimeOffsetValue("previousAiring", PreviousAiring);
            writer.WriteStringValue("profileName", ProfileName);
            writer.WriteIntValue("qualityProfileId", QualityProfileId);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.Ratings>("ratings", Ratings);
            writer.WriteStringValue("remotePoster", RemotePoster);
            writer.WriteStringValue("rootFolderPath", RootFolderPath);
            writer.WriteIntValue("runtime", Runtime);
            writer.WriteBoolValue("seasonFolder", SeasonFolder);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sonarr.OpenApiClient.Models.SeasonResource>("seasons", Seasons);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesTypes>("seriesType", SeriesType);
            writer.WriteStringValue("sortTitle", SortTitle);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesStatisticsResource>("statistics", Statistics);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesStatusType>("status", Status);
            writer.WriteCollectionOfPrimitiveValues<int?>("tags", Tags);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("titleSlug", TitleSlug);
            writer.WriteIntValue("tmdbId", TmdbId);
            writer.WriteIntValue("tvdbId", TvdbId);
            writer.WriteIntValue("tvMazeId", TvMazeId);
            writer.WriteIntValue("tvRageId", TvRageId);
            writer.WriteBoolValue("useSceneNumbering", UseSceneNumbering);
            writer.WriteIntValue("year", Year);
        }
    }
}
#pragma warning restore CS0618
