// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SeriesEditorResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The addImportListExclusion property</summary>
        public bool? AddImportListExclusion { get; set; }
        /// <summary>The applyTags property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.ApplyTags? ApplyTags { get; set; }
        /// <summary>The deleteFiles property</summary>
        public bool? DeleteFiles { get; set; }
        /// <summary>The monitored property</summary>
        public bool? Monitored { get; set; }
        /// <summary>The monitorNewItems property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.NewItemMonitorTypes? MonitorNewItems { get; set; }
        /// <summary>The moveFiles property</summary>
        public bool? MoveFiles { get; set; }
        /// <summary>The qualityProfileId property</summary>
        public int? QualityProfileId { get; set; }
        /// <summary>The rootFolderPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootFolderPath { get; set; }
#nullable restore
#else
        public string RootFolderPath { get; set; }
#endif
        /// <summary>The seasonFolder property</summary>
        public bool? SeasonFolder { get; set; }
        /// <summary>The seriesIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? SeriesIds { get; set; }
#nullable restore
#else
        public List<int?> SeriesIds { get; set; }
#endif
        /// <summary>The seriesType property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Models.SeriesTypes? SeriesType { get; set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Tags { get; set; }
#nullable restore
#else
        public List<int?> Tags { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.SeriesEditorResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.SeriesEditorResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.SeriesEditorResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addImportListExclusion", n => { AddImportListExclusion = n.GetBoolValue(); } },
                { "applyTags", n => { ApplyTags = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.ApplyTags>(); } },
                { "deleteFiles", n => { DeleteFiles = n.GetBoolValue(); } },
                { "monitorNewItems", n => { MonitorNewItems = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.NewItemMonitorTypes>(); } },
                { "monitored", n => { Monitored = n.GetBoolValue(); } },
                { "moveFiles", n => { MoveFiles = n.GetBoolValue(); } },
                { "qualityProfileId", n => { QualityProfileId = n.GetIntValue(); } },
                { "rootFolderPath", n => { RootFolderPath = n.GetStringValue(); } },
                { "seasonFolder", n => { SeasonFolder = n.GetBoolValue(); } },
                { "seriesIds", n => { SeriesIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "seriesType", n => { SeriesType = n.GetEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesTypes>(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("addImportListExclusion", AddImportListExclusion);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.ApplyTags>("applyTags", ApplyTags);
            writer.WriteBoolValue("deleteFiles", DeleteFiles);
            writer.WriteBoolValue("monitored", Monitored);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.NewItemMonitorTypes>("monitorNewItems", MonitorNewItems);
            writer.WriteBoolValue("moveFiles", MoveFiles);
            writer.WriteIntValue("qualityProfileId", QualityProfileId);
            writer.WriteStringValue("rootFolderPath", RootFolderPath);
            writer.WriteBoolValue("seasonFolder", SeasonFolder);
            writer.WriteCollectionOfPrimitiveValues<int?>("seriesIds", SeriesIds);
            writer.WriteEnumValue<global::Soenneker.Sonarr.OpenApiClient.Models.SeriesTypes>("seriesType", SeriesType);
            writer.WriteCollectionOfPrimitiveValues<int?>("tags", Tags);
        }
    }
}
#pragma warning restore CS0618
