// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SortDirection
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        Default,
        #pragma warning restore CS1591
        [EnumMember(Value = "ascending")]
        #pragma warning disable CS1591
        Ascending,
        #pragma warning restore CS1591
        [EnumMember(Value = "descending")]
        #pragma warning disable CS1591
        Descending,
        #pragma warning restore CS1591
    }
}
