// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TagDetailsResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The autoTagIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AutoTagIds { get; set; }
#nullable restore
#else
        public List<int?> AutoTagIds { get; set; }
#endif
        /// <summary>The delayProfileIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? DelayProfileIds { get; set; }
#nullable restore
#else
        public List<int?> DelayProfileIds { get; set; }
#endif
        /// <summary>The downloadClientIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? DownloadClientIds { get; set; }
#nullable restore
#else
        public List<int?> DownloadClientIds { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The importListIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? ImportListIds { get; set; }
#nullable restore
#else
        public List<int?> ImportListIds { get; set; }
#endif
        /// <summary>The indexerIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? IndexerIds { get; set; }
#nullable restore
#else
        public List<int?> IndexerIds { get; set; }
#endif
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The notificationIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? NotificationIds { get; set; }
#nullable restore
#else
        public List<int?> NotificationIds { get; set; }
#endif
        /// <summary>The restrictionIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? RestrictionIds { get; set; }
#nullable restore
#else
        public List<int?> RestrictionIds { get; set; }
#endif
        /// <summary>The seriesIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? SeriesIds { get; set; }
#nullable restore
#else
        public List<int?> SeriesIds { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.TagDetailsResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.TagDetailsResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.TagDetailsResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoTagIds", n => { AutoTagIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "delayProfileIds", n => { DelayProfileIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "downloadClientIds", n => { DownloadClientIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "importListIds", n => { ImportListIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "indexerIds", n => { IndexerIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "notificationIds", n => { NotificationIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "restrictionIds", n => { RestrictionIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "seriesIds", n => { SeriesIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("autoTagIds", AutoTagIds);
            writer.WriteCollectionOfPrimitiveValues<int?>("delayProfileIds", DelayProfileIds);
            writer.WriteCollectionOfPrimitiveValues<int?>("downloadClientIds", DownloadClientIds);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfPrimitiveValues<int?>("importListIds", ImportListIds);
            writer.WriteCollectionOfPrimitiveValues<int?>("indexerIds", IndexerIds);
            writer.WriteStringValue("label", Label);
            writer.WriteCollectionOfPrimitiveValues<int?>("notificationIds", NotificationIds);
            writer.WriteCollectionOfPrimitiveValues<int?>("restrictionIds", RestrictionIds);
            writer.WriteCollectionOfPrimitiveValues<int?>("seriesIds", SeriesIds);
        }
    }
}
#pragma warning restore CS0618
