// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TaskResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The interval property</summary>
        public int? Interval { get; set; }
        /// <summary>The lastDuration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastDuration { get; private set; }
#nullable restore
#else
        public string LastDuration { get; private set; }
#endif
        /// <summary>The lastExecution property</summary>
        public DateTimeOffset? LastExecution { get; set; }
        /// <summary>The lastStartTime property</summary>
        public DateTimeOffset? LastStartTime { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The nextExecution property</summary>
        public DateTimeOffset? NextExecution { get; set; }
        /// <summary>The taskName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskName { get; set; }
#nullable restore
#else
        public string TaskName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.TaskResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.TaskResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.TaskResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetIntValue(); } },
                { "interval", n => { Interval = n.GetIntValue(); } },
                { "lastDuration", n => { LastDuration = n.GetStringValue(); } },
                { "lastExecution", n => { LastExecution = n.GetDateTimeOffsetValue(); } },
                { "lastStartTime", n => { LastStartTime = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nextExecution", n => { NextExecution = n.GetDateTimeOffsetValue(); } },
                { "taskName", n => { TaskName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("interval", Interval);
            writer.WriteDateTimeOffsetValue("lastExecution", LastExecution);
            writer.WriteDateTimeOffsetValue("lastStartTime", LastStartTime);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("nextExecution", NextExecution);
            writer.WriteStringValue("taskName", TaskName);
        }
    }
}
#pragma warning restore CS0618
