// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TrackedDownloadState
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "downloading")]
        #pragma warning disable CS1591
        Downloading,
        #pragma warning restore CS1591
        [EnumMember(Value = "importBlocked")]
        #pragma warning disable CS1591
        ImportBlocked,
        #pragma warning restore CS1591
        [EnumMember(Value = "importPending")]
        #pragma warning disable CS1591
        ImportPending,
        #pragma warning restore CS1591
        [EnumMember(Value = "importing")]
        #pragma warning disable CS1591
        Importing,
        #pragma warning restore CS1591
        [EnumMember(Value = "imported")]
        #pragma warning disable CS1591
        Imported,
        #pragma warning restore CS1591
        [EnumMember(Value = "failedPending")]
        #pragma warning disable CS1591
        FailedPending,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "ignored")]
        #pragma warning disable CS1591
        Ignored,
        #pragma warning restore CS1591
    }
}
