// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateMechanism
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "builtIn")]
        #pragma warning disable CS1591
        BuiltIn,
        #pragma warning restore CS1591
        [EnumMember(Value = "script")]
        #pragma warning disable CS1591
        Script,
        #pragma warning restore CS1591
        [EnumMember(Value = "external")]
        #pragma warning disable CS1591
        External,
        #pragma warning restore CS1591
        [EnumMember(Value = "apt")]
        #pragma warning disable CS1591
        Apt,
        #pragma warning restore CS1591
        [EnumMember(Value = "docker")]
        #pragma warning disable CS1591
        Docker,
        #pragma warning restore CS1591
    }
}
