// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The branch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Branch { get; set; }
#nullable restore
#else
        public string Branch { get; set; }
#endif
        /// <summary>The changes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sonarr.OpenApiClient.Models.UpdateChanges? Changes { get; set; }
#nullable restore
#else
        public global::Soenneker.Sonarr.OpenApiClient.Models.UpdateChanges Changes { get; set; }
#endif
        /// <summary>The fileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>The hash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hash { get; set; }
#nullable restore
#else
        public string Hash { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The installable property</summary>
        public bool? Installable { get; set; }
        /// <summary>The installed property</summary>
        public bool? Installed { get; set; }
        /// <summary>The installedOn property</summary>
        public DateTimeOffset? InstalledOn { get; set; }
        /// <summary>The latest property</summary>
        public bool? Latest { get; set; }
        /// <summary>The releaseDate property</summary>
        public DateTimeOffset? ReleaseDate { get; set; }
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.UpdateResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sonarr.OpenApiClient.Models.UpdateResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sonarr.OpenApiClient.Models.UpdateResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "branch", n => { Branch = n.GetStringValue(); } },
                { "changes", n => { Changes = n.GetObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.UpdateChanges>(global::Soenneker.Sonarr.OpenApiClient.Models.UpdateChanges.CreateFromDiscriminatorValue); } },
                { "fileName", n => { FileName = n.GetStringValue(); } },
                { "hash", n => { Hash = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "installable", n => { Installable = n.GetBoolValue(); } },
                { "installed", n => { Installed = n.GetBoolValue(); } },
                { "installedOn", n => { InstalledOn = n.GetDateTimeOffsetValue(); } },
                { "latest", n => { Latest = n.GetBoolValue(); } },
                { "releaseDate", n => { ReleaseDate = n.GetDateTimeOffsetValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("branch", Branch);
            writer.WriteObjectValue<global::Soenneker.Sonarr.OpenApiClient.Models.UpdateChanges>("changes", Changes);
            writer.WriteStringValue("fileName", FileName);
            writer.WriteStringValue("hash", Hash);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("installable", Installable);
            writer.WriteBoolValue("installed", Installed);
            writer.WriteDateTimeOffsetValue("installedOn", InstalledOn);
            writer.WriteBoolValue("latest", Latest);
            writer.WriteDateTimeOffsetValue("releaseDate", ReleaseDate);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("version", Version);
        }
    }
}
#pragma warning restore CS0618
