// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Downloadclient;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Host;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Importlist;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Indexer;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Mediamanagement;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Naming;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Ui;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Api.V3.Config
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\config
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConfigRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The downloadclient property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Downloadclient.DownloadclientRequestBuilder Downloadclient
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Downloadclient.DownloadclientRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The host property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Host.HostRequestBuilder Host
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Host.HostRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The importlist property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Importlist.ImportlistRequestBuilder Importlist
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Importlist.ImportlistRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The indexer property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Indexer.IndexerRequestBuilder Indexer
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Indexer.IndexerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mediamanagement property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Mediamanagement.MediamanagementRequestBuilder Mediamanagement
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Mediamanagement.MediamanagementRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The naming property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Naming.NamingRequestBuilder Naming
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Naming.NamingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ui property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Ui.UiRequestBuilder Ui
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.Ui.UiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.ConfigRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/config", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Config.ConfigRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/config", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
