// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sonarr.OpenApiClient.Api.V3.History.Failed;
using Soenneker.Sonarr.OpenApiClient.Api.V3.History.Series;
using Soenneker.Sonarr.OpenApiClient.Api.V3.History.Since;
using Soenneker.Sonarr.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Api.V3.History
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\history
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HistoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The failed property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.Failed.FailedRequestBuilder Failed
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.Failed.FailedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The series property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.Series.SeriesRequestBuilder Series
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.Series.SeriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The since property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.Since.SinceRequestBuilder Since
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.Since.SinceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.HistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HistoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/history{?downloadId*,episodeId*,eventType*,includeEpisode*,includeSeries*,languages*,page*,pageSize*,quality*,seriesIds*,sortDirection*,sortKey*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.HistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HistoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/history{?downloadId*,episodeId*,eventType*,includeEpisode*,includeSeries*,languages*,page*,pageSize*,quality*,seriesIds*,sortDirection*,sortKey*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.HistoryResourcePagingResource"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sonarr.OpenApiClient.Models.HistoryResourcePagingResource?> GetAsync(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.HistoryRequestBuilder.HistoryRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sonarr.OpenApiClient.Models.HistoryResourcePagingResource> GetAsync(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.HistoryRequestBuilder.HistoryRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sonarr.OpenApiClient.Models.HistoryResourcePagingResource>(requestInfo, global::Soenneker.Sonarr.OpenApiClient.Models.HistoryResourcePagingResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.HistoryRequestBuilder.HistoryRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.HistoryRequestBuilder.HistoryRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.HistoryRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.HistoryRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.HistoryRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class HistoryRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("downloadId")]
            public string? DownloadId { get; set; }
#nullable restore
#else
            [QueryParameter("downloadId")]
            public string DownloadId { get; set; }
#endif
            [QueryParameter("episodeId")]
            public int? EpisodeId { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("eventType")]
            public int?[]? EventType { get; set; }
#nullable restore
#else
            [QueryParameter("eventType")]
            public int?[] EventType { get; set; }
#endif
            [QueryParameter("includeEpisode")]
            public bool? IncludeEpisode { get; set; }
            [QueryParameter("includeSeries")]
            public bool? IncludeSeries { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("languages")]
            public int?[]? Languages { get; set; }
#nullable restore
#else
            [QueryParameter("languages")]
            public int?[] Languages { get; set; }
#endif
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("quality")]
            public int?[]? Quality { get; set; }
#nullable restore
#else
            [QueryParameter("quality")]
            public int?[] Quality { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("seriesIds")]
            public int?[]? SeriesIds { get; set; }
#nullable restore
#else
            [QueryParameter("seriesIds")]
            public int?[] SeriesIds { get; set; }
#endif
            [Obsolete("This property is deprecated, use SortDirectionAsSortDirection instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortDirection")]
            public string? SortDirection { get; set; }
#nullable restore
#else
            [QueryParameter("sortDirection")]
            public string SortDirection { get; set; }
#endif
            [QueryParameter("sortDirection")]
            public global::Soenneker.Sonarr.OpenApiClient.Models.SortDirection? SortDirectionAsSortDirection { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortKey")]
            public string? SortKey { get; set; }
#nullable restore
#else
            [QueryParameter("sortKey")]
            public string SortKey { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class HistoryRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.History.HistoryRequestBuilder.HistoryRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
