// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.ActionNamespace;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Bulk;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Item;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Schema;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Test;
using Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Testall;
using Soenneker.Sonarr.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\indexer
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IndexerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The action property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.ActionNamespace.ActionRequestBuilder Action
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.ActionNamespace.ActionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bulk property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Bulk.BulkRequestBuilder Bulk
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Bulk.BulkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The schema property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Schema.SchemaRequestBuilder Schema
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Schema.SchemaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The test property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Test.TestRequestBuilder Test
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Test.TestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The testall property</summary>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Testall.TestallRequestBuilder Testall
        {
            get => new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Testall.TestallRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Sonarr.OpenApiClient.api.v3.indexer.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Item.IndexerItemRequestBuilder"/></returns>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Item.IndexerItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.Item.IndexerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.IndexerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IndexerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/indexer{?forceSave*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.IndexerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IndexerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/indexer{?forceSave*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource>(requestInfo, global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource?> PostAsync(global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource body, Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.IndexerRequestBuilder.IndexerRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource> PostAsync(global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource body, Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.IndexerRequestBuilder.IndexerRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource>(requestInfo, global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource body, Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.IndexerRequestBuilder.IndexerRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Sonarr.OpenApiClient.Models.IndexerResource body, Action<RequestConfiguration<global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.IndexerRequestBuilder.IndexerRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.IndexerRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.IndexerRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sonarr.OpenApiClient.Api.V3.Indexer.IndexerRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class IndexerRequestBuilderPostQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("forceSave")]
            public bool? ForceSave { get; set; }
        }
    }
}
#pragma warning restore CS0618
